heat_template_version: rocky

description: >
  OpenStack Neutron ML2/CiscoAci plugin configured with Puppet

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  # Config specific parameters, to be provided via parameter_defaults
  ACIApicHosts:
    default: {}
    description: APIC ip address
    type: string
    default: 1.1.1.1
  ACIApicUsername:
    type: string
    default: admin
  ACIApicPassword:
    type: string
    default: 'password'
  ACIApicSystemId:
    description: The System ID is used to support running multiple OpenStack
                 clouds on a single ACI fabric. Resources created in ACI are
                 annotated with the System ID to associate the resource with
                 a given OpenStack cloud. The System ID is also used in the
                 generation of some name strings used for ACI resources as
                 well. In most installations, the System ID must not exceed
                 the default maximum length of 16 characters. However, in
                 some special cases, it can be increased, which requires
                 also setting the ACIApicSystemIdMaxLength parameter.
    type: string
    default: 'aci_openstack'
  ACIApicSystemIdMaxLength:
    description: Maximmum length of the ACIApicSystemId. Please consult the
                 business unit before changing this value from the default.
    type: number
    default: 16
  ACIApicInfraVlan:
    type: number
    default: 4093
  ACIApicEntityProfile:
    type: string
    default: 'openstack-aep'
  ACIMechanismDrivers:
    type: string
    default: 'apic_aim'
    description: >
     set the value to the ml2 drivers required. In most cases the default is sufficient,
     in cases when using sriov for example set it to 'sriovnicswitch,apic_aim'
  ACIApicInfraSubnetGateway:
    type: string
    default: '10.0.0.30'
  ACIApicInfraAnycastAddr:
    type: string
    default: '10.0.0.32'
  ACIOpflexUplinkInterface:
    type: string
    default: 'nic1'
  ACIOpflexInterfaceType:
    type: string
    default: 'linux'
    description: >
      Valid values are 'linux' or 'ovs'. This determines whether the infra vlan interface
      is created as a linux interface or an OVS interface. For openshift on openstack, the
      interface should be a OVS interface.
  ACIOpflexDisabledFeatures:
    type: comma_delimited_list
    default: ""
    description: >
      Valid values are "erspan". This determines whether a given feature is supported
      by the vSwitch in the underlying distribution, and therefore can be enabled in the
      opflex-agent.
  ACIOpflexInterfaceMTU:
    type: number
    default: 1600
  ACIOpflexBridgeToPatch:
    type: string
    default: 'br-ex'
    description: >
     When opflex is used in VLAN encap mode, the interface connected to ACI fabric should
     be part of integration bridge br-int. In some network configuration, the interface could
     already be part of other bridge for example br-ex. Setting this value to br-ex will create
     a patch interface between br-int and br-ex. If set to empty string, no patch will be created
  ACIOpflexEncapMode:
    type: string
    default: 'vxlan'
    constraints:
      - allowed_values: ['vlan', 'vxlan']
  ACIOpflexVlanRange:
    default: ''
    description: >
      The vlan ranges to use when encap mode is vlan. If ACIOpflexEncapMode is vxlan, this option is
      ignored
    type: comma_delimited_list
  ACIHostLinks:
    type: json
    default: {}
  ACIVpcPairs:
    type: string
    default: ''
    description: comma separated string of switch id's which form vpc pairs. Example '101:102,103:104'
  ACIOptimizedDhcp:
    type: boolean
    default: true
    description: Enable Optimized DHCP service
  ACIOptimizedMetadata:
    type: boolean
    default: true
    description: Enable Optimized Metadata service
  ACIScopeNames:
    type: boolean
    default: false
    description: Enable scoping of names with apic_system_id
  ACIScopeInfra:
    type: boolean
    default: false
    description: Enable scoping of Infra names with apic_system_id
  NeutronPassword:
    description: The password for the neutron service and db account, used by neutron agents.
    type: string
    hidden: true
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  NeutronPluginExtensions:
    default: "apic_aim,port_security"
    description: |
        Comma-separated list of extensions enabled for the Neutron plugin.
    type: comma_delimited_list
  NeutronNetworkVLANRanges:
    default: ''
    description: >
      Use this option if using hierarchial portbinding. This value will be
      plugged into ml2_type_vlan section of plugin.ini if it is not blank
      example value datacentre:1000:2000
    type: comma_delimited_list
  NeutronPhysicalDevMappings:
    description: >
      List of <physical_network>:<physical device>
      All physical networks listed in network_vlan_ranges
      on the server should have mappings to appropriate
      interfaces on each agent.
    type: comma_delimited_list
    default: ""
  OpflexEndpointReqTimeout:
    default: 10
    type: number
  OpflexNatMtuSize:
    default: 0
    type: number
  AciKeystoneNotificationPurge:
    type: boolean
    default: true
    description: >
      When true, act on keystone notifications to purge
  AciKeystoneNotificationExchange:
    type: string
    default: 'keystone'
    description: >
      When AciKeystoneNotificationPurge is set to true,
      determines which exchange to use for notifications.
  AciKeystoneNotificationTopic:
    type: string
    default: 'notifications'
    description: >
      When AciKeystoneNotificationPurge is set to true,
      determines which topic to use for notifications.
  AciKeystoneNotificationPool:
    type: string
    default: None
    description: >
      When AciKeystoneNotificationPurge is set to true,
      determines which pool to use for notifications.
      This value should only be configured to a value other
      than 'None' when there are other notification listeners
      subscribed to the same keystone exchange and topic, whose
      pool is set to 'None'.
  AciOpenvswitch:
    type: boolean
    default: false
  AciTenantNetworkType:
    type: string
    default: 'opflex'
  IntelCnaNicDisableLLDP:
    type: boolean
    default: true
  ACIAimDebug:
    type: boolean
    default: false
  NeutronExternalBridge:
    type: string
    default: 'br-ex'
    description: >
       Opflex depends on knowing what the external bridge name is, which by default is br-ex
       If neutron configuration was changed to some other name, this variable needs to be set
       to the same value.
  AciExternalRoutedDomain:
    type: string
    default: ""
  ACIEnableBondWatchService:
    type: boolean
    default: false
    description: Enable and start apic-bond-watch service

resources:

  NeutronMl2Base:
    type: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-plugin-ml2.yaml
    properties:
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}

outputs:
  role_data:
    description: Role data for the Neutron ML2/CiscoAci plugin
    value:
      service_name: neutron_plugin_ml2_ciscoaci
      config_settings:
        map_merge:
          - get_attr: [NeutronMl2Base, role_data, config_settings]
          - ciscoaci::aim_config::neutron_sql_connection:
              make_url:
                scheme: {get_param: [EndpointMap, MysqlInternal, protocol]}
                username: neutron
                password: {get_param: NeutronPassword}
                host: {get_param: [EndpointMap, MysqlInternal, host]}
                path: /ovs_neutron
                query:
                  read_default_file: /etc/my.cnf.d/tripleo.cnf
                  read_default_group: tripleo
            ciscoaci::aim_config::aci_apic_hosts: {get_param: ACIApicHosts}
            ciscoaci::aim_config::aci_apic_username: {get_param: ACIApicUsername}
            ciscoaci::aim_config::aci_apic_password: {get_param: ACIApicPassword}
            ciscoaci::ml2::aci_apic_systemid: {get_param: ACIApicSystemId}
            ciscoaci::aim_config::aci_apic_systemid: {get_param: ACIApicSystemId}
            ciscoaci::aim_config::aci_apic_systemid_length: {get_param: ACIApicSystemIdMaxLength}
            ciscoaci::aim_config::aci_apic_aep: {get_param: ACIApicEntityProfile}
            ciscoaci::aim_config::aci_vpc_pairs: {get_param: ACIVpcPairs}
            ciscoaci::aim_config::aci_encap_mode: {get_param: ACIOpflexEncapMode}
            ciscoaci::aim_config::aci_opflex_vlan_range: {get_param: ACIOpflexVlanRange}
            ciscoaci::aim_config::aci_scope_names: {get_param: ACIScopeNames}
            ciscoaci::aim_config::aci_scope_infra: {get_param: ACIScopeInfra}
            ciscoaci::aim_config::aci_host_links: {get_param: ACIHostLinks}
            ciscoaci::ml2::aci_optimized_dhcp: {get_param: ACIOptimizedDhcp}
            ciscoaci::ml2::aci_optimized_metadata: {get_param: ACIOptimizedMetadata}
            ciscoaci::aim_config::aci_scope_names: {get_param: ACIScopeNames}
            ciscoaci::aim_config::aci_scope_infra: {get_param: ACIScopeInfra}
            ciscoaci::aim_config::aci_aim_debug: {get_param: ACIAimDebug}
            ciscoaci::ml2::keystone_auth_admin_url: { get_param: [ EndpointMap, NeutronAdmin, uri ] }
            ciscoaci::ml2::keystone_auth_password: {get_param: NeutronPassword}
            ciscoaci::ml2::aci_mechanism_drivers: {get_param: ACIMechanismDrivers}
            ciscoaci::opflex::aci_apic_systemid: {get_param: ACIApicSystemId}
            ciscoaci::opflex::aci_apic_infravlan: {get_param: ACIApicInfraVlan}
            ciscoaci::opflex::aci_apic_infra_subnet_gateway: {get_param: ACIApicInfraSubnetGateway}
            ciscoaci::opflex::aci_apic_infra_anycast_address: {get_param: ACIApicInfraAnycastAddr}
            ciscoaci::opflex::aci_opflex_uplink_interface: {get_param: ACIOpflexUplinkInterface}
            ciscoaci::opflex::aci_opflex_encap_mode: {get_param: ACIOpflexEncapMode}
            ciscoaci::opflex::opflex_disabled_features: {get_param: ACIOpflexDisabledFeatures}
            ciscoaci::opflex::opflex_target_bridge_to_patch: {get_param: ACIOpflexBridgeToPatch}
            ciscoaci::opflex::opflex_interface_type: {get_param: ACIOpflexInterfaceType}
            ciscoaci::opflex::opflex_interface_mtu: {get_param: ACIOpflexInterfaceMTU}
            ciscoaci::ml2::use_openvswitch: {get_param: AciOpenvswitch}
            ciscoaci::aim_config::use_openvswitch: {get_param: AciOpenvswitch}
            ciscoaci::aim_config::rabbit_password: {get_param: RabbitPassword}
            ciscoaci::aim_config::rabbit_user: {get_param: RabbitUserName}
            ciscoaci::aim_config::rabbit_port: {get_param: RabbitClientPort}
            ciscoaci::ml2::extension_drivers: { get_param: NeutronPluginExtensions }
            ciscoaci::ml2::neutron_network_vlan_ranges: {get_param: NeutronNetworkVLANRanges}
            ciscoaci::aim_config::neutron_network_vlan_ranges: {get_param: NeutronNetworkVLANRanges}
            ciscoaci::aim_config::physical_device_mappings: {get_param: NeutronPhysicalDevMappings}
            ciscoaci::ml2::opflex_endpoint_request_timeout: {get_param: OpflexEndpointReqTimeout}
            ciscoaci::ml2::opflex_nat_mtu_size: {get_param: OpflexNatMtuSize}
            ciscoaci::ml2::enable_keystone_notification_purge: {get_param:  AciKeystoneNotificationPurge}
            ciscoaci::ml2::keystone_notification_exchange: {get_param:  AciKeystoneNotificationExchange}
            ciscoaci::ml2::keystone_notification_topic: {get_param:  AciKeystoneNotificationTopic}
            ciscoaci::ml2::keystone_notification_pool: {get_param:  AciKeystoneNotificationPool}
            ciscoaci::ml2::tenant_network_types: {get_param: AciTenantNetworkType}
            ciscoaci::ml2::intel_cna_nic_disable_lldp: {get_param: IntelCnaNicDisableLLDP}
            ciscoaci::ml2::aci_external_routed_domain: {get_param: AciExternalRoutedDomain}
            ciscoaci::opflex::neutron_external_bridge: {get_param: NeutronExternalBridge}
            ciscoaci::opflex::opflex_enable_bond_watch: {get_param: ACIEnableBondWatchService}
            neutron::policy::policy_path: "/etc/neutron/merged-policy.json"
      step_config: |
        include tripleo::profile::base::ciscoaci_ml2
      metadata_settings:
        get_attr: [NeutronMl2Base, role_data, metadata_settings]
      external_upgrade_tasks:
        - when:
            - step|int == 1
          tags:
            - never
            - system_upgrade_transfer_data
            - system_upgrade_stop_services
          block:
            - name: Dummy
              vars:
                tripleo_delegate_to: "{{ groups['neutron_api'] | default([]) }}"
