heat_template_version: rocky

description: >
  OpenStack Neutron Compute Cisco ACI plugin

parameters:
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ACIApicSystemId:
    type: string
    default: 'aci_openstack'
  ACIApicInfraVlan:
    type: number
    default: 4093
  ACIApicInfraSubnetGateway:
    type: string
    default: '10.0.0.30'
  ACIApicInfraAnycastAddr:
    type: string
    default: '10.0.0.32'
  ACIOpflexUplinkInterface:
    type: string
    default: 'nic1'
  ACIOpflexInterfaceType:
    type: string
    default: 'linux'
    description: >
      Valid values are 'linux' or 'ovs'. This determines whether the infra vlan interface
      is created as a linux interface or an OVS interface. For openshift on openstack, the
      interface should be a OVS interface.
  ACIOpflexDisabledFeatures:
    type: comma_delimited_list
    default: ""
    description: >
      Valid values are "erspan". This determines whether a given feature is supported
      by the vSwitch in the underlying distribution, and therefore can be enabled in the
      opflex-agent.
  ACIOpflexInterfaceMTU:
    type: number
    default: 1600
  ACIOpflexBridgeToPatch:
    type: string
    default: 'br-ex'
    description: >
     When opflex is used in VLAN encap mode, the interface connected to ACI fabric should
     be part of integration bridge br-int. In some network configuration, the interface could
     already be part of other bridge for example br-ex. Setting this value to br-ex will create
     a patch interface between br-int and br-ex. If set to empty string, no patch will be created
  ACIOpflexEncapMode:
    type: string
    default: 'vxlan'  
    constraints:
      - allowed_values: ['vlan', 'vxlan']
  ACIEnableBondWatchService:
    type: boolean
    default: false
    description: Enable and start apic-bond-watch service
  AciOpenvswitch:
    type: boolean
    default: false
  IntelCnaNicDisableLLDP:
    type: boolean
    default: true
  NeutronExternalBridge:
    type: string
    default: 'br-ex'
    description: >
       Opflex depends on knowing what the external bridge name is, which by default is br-ex
       If neutron configuration was changed to some other name, this variable needs to be set
       to the same value.
  RabbitPassword:
    description: The password for RabbitMQ
    type: string
    hidden: true
  RabbitUserName:
    default: guest
    description: The username for RabbitMQ
    type: string
  RabbitClientUseSSL:
    default: false
    description: >
        Rabbit client subscriber parameter to specify
        an SSL connection to the RabbitMQ host.
    type: string
  RabbitClientPort:
    default: 5672
    description: Set rabbit subscriber port, change this if using SSL
    type: number
  NotificationDriver:
    type: string
    default: 'messagingv2'
    description: Driver or drivers to handle sending notifications.
    constraints:
      - allowed_values: [ 'messagingv2', 'noop' ]
  NeutronCorePlugin:
    default: 'ml2'
    description: |
        The core plugin for Neutron. The value should be the entrypoint to be loaded
        from neutron.core_plugins namespace.
    type: string
  NeutronServicePlugins:
    default: "router,qos,segments,trunk"
    description: |
        Comma-separated list of service plugin entrypoints to be loaded from the
        neutron.service_plugins namespace.
    type: comma_delimited_list
resources:
  NeutronBase:
    type: /usr/share/openstack-tripleo-heat-templates/deployment/neutron/neutron-base.yaml
    properties:
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Neutron compute Cisco ACI plugin
    value:
      service_name: neutron_plugin_compute_ciscoaci
      config_settings:
        map_merge:
          - get_attr: [NeutronBase, role_data, config_settings]
            neutron::rabbit_password: {get_param: RabbitPassword}
            neutron::rabbit_user: {get_param: RabbitUserName}
            neutron::rabbit_use_ssl: {get_param: RabbitClientUseSSL}
            neutron::rabbit_port: {get_param: RabbitClientPort}
            neutron::notification_driver: {get_param: NotificationDriver}
            neutron::core_plugin: {get_param: NeutronCorePlugin}
            neutron::service_plugins: {get_param: NeutronServicePlugins}
            ciscoaci::opflex::aci_apic_systemid: {get_param: ACIApicSystemId}
            ciscoaci::opflex::aci_apic_infravlan: {get_param: ACIApicInfraVlan}
            ciscoaci::opflex::aci_apic_infra_subnet_gateway: {get_param: ACIApicInfraSubnetGateway}
            ciscoaci::opflex::aci_apic_infra_anycast_address: {get_param: ACIApicInfraAnycastAddr}    
            ciscoaci::opflex::aci_opflex_uplink_interface: {get_param: ACIOpflexUplinkInterface}
            ciscoaci::opflex::aci_opflex_encap_mode: {get_param: ACIOpflexEncapMode}
            ciscoaci::opflex::opflex_disabled_features: {get_param: ACIOpflexDisabledFeatures}
            ciscoaci::opflex::opflex_enable_bond_watch: {get_param: ACIEnableBondWatchService}
            ciscoaci::opflex::opflex_target_bridge_to_patch: {get_param: ACIOpflexBridgeToPatch}
            ciscoaci::opflex::opflex_interface_type: {get_param: ACIOpflexInterfaceType}
            ciscoaci::opflex::opflex_interface_mtu: {get_param: ACIOpflexInterfaceMTU}
            ciscoaci::compute::use_openvswitch: {get_param: AciOpenvswitch}
            ciscoaci::compute::intel_cna_nic_disable_lldp: {get_param: IntelCnaNicDisableLLDP}
            ciscoaci::opflex::neutron_external_bridge: {get_param: NeutronExternalBridge}
      step_config: |
        include tripleo::profile::base::ciscoaci_compute
      external_upgrade_tasks:
        - when:
            - step|int == 1
          tags:
            - never
            - system_upgrade_transfer_data
            - system_upgrade_stop_services
          block:
            - name: Dummy2
              ignore_errors: true
              file:
                  path: /tmp/neutron_compute
                  state: absent
              vars:
                tripleo_delegate_to: "{{ groups['neutron_api'] | default([]) }}"
