heat_template_version: queens

description: >
  OpenStack Cisco Aci lldp service

parameters:
  ContainerCiscoLldpImage:
    description: image
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  UpgradeRemoveUnusedPackages:
    default: false
    description: Remove package if the service is being disabled during upgrade
    type: boolean

resources:

  ContainersCommon:
    type: /usr/share/openstack-tripleo-heat-templates/deployment/containers-common.yaml

outputs:
  role_data:
    description: Role data for Cisco Aci LLDP service
    value:
      service_name: ciscoaci_lldp_service
      puppet_config:
        config_volume: neutron
        puppet_tags: 
        step_config: include ciscoaci::lldp
        config_image: {get_param: ContainerCiscoLldpImage}
        volumes:
          - /lib/modules:/lib/modules:ro
      kolla_config:
        /var/lib/kolla/config_files/ciscoaci_lldp.json:
          command: /bin/supervisord -c /etc/neutron/ciscoaci/ciscoaci_lldp_supervisord.conf
          config_files:
            - source: "/var/lib/kolla/config_files/src/*"
              dest: "/"
              merge: true
              preserve_properties: true
          permissions:
            - path: /var/log/neutron
              owner: neutron:neutron
              recurse: true
      container_config_scripts: {get_attr: [ContainersCommon, container_config_scripts]}
      docker_config:
        step_4:
          ciscoaci_lldp_agent:
            start_order: 10
            image: {get_param: ContainerCiscoLldpImage}
            net: host
            pid: host
            user: root
            privileged: true
            restart: always
            healthcheck:
              test: /etc/neutron/ciscoaci/lldp_healthcheck
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/ciscoaci_lldp.json:/var/lib/kolla/config_files/config.json:ro
                  - /lib/modules:/lib/modules:ro
                  - /var/lib/config-data/puppet-generated/neutron/:/var/lib/kolla/config_files/src:ro
                  - /var/log/containers/neutron:/var/log/neutron
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
      metadata_settings:
      host_prep_tasks: 
            - name: create persistent directories
              file:
                path: /var/log/containers/neutron
                state: directory
      external_upgrade_tasks:
        - when:
            - step|int == 1
          tags:
            - never
            - system_upgrade_transfer_data
            - system_upgrade_stop_services
          block:
            - name: Stop lldp container
              import_role:
                name: tripleo-container-stop
              vars:
                tripleo_containers_to_stop:
                  - ciscoaci_lldp_agent
                tripleo_delegate_to: "{{ groups['neutron_api'] | default([]) }}"
